bookcase_authors:
    resource: "@BookcaseBundle/Controller/AuthorsController.php"
    type:     annotation

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

bookcase:
    resource: "@BookcaseBundle/Resources/config/routing.yml"
    prefix:   /

