<?php

namespace BookcaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorsRepository extends EntityRepository
{
}
