<?php

namespace BookcaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * authorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class authorRepository extends EntityRepository
{
}
