<?php

namespace BookcaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AutorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorsRepository extends EntityRepository
{
}
